version: "3.9"
   
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'dockdockgoose'
      MONGO_DB: 'stocksite_db_dev'
    command: mongod --auth
    volumes:
      - ./stocksite/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - data-db:/data/db
    ports: 
      - 27017:27017
    networks: 
      - localnet

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_MONGODB_BASICAUTH_PASSWORD: 'duck'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'dockdockgoose'
    depends_on: 
      - mongodb
    links:
      - mongodb
    networks: 
      - localnet

  redis:
    restart: always
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks: 
      - localnet

  web:
    build: ./stocksite
    restart: always
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./stocksite/:/code
    ports:
      - "8000:8000"
    links:
      - mongodb
      - redis
    networks: 
      - localnet
    env_file: 
      - ./.env.dev

volumes:
  data-db:

networks:
  localnet:
    driver: 'bridge'