# Generated by Django 3.0.5 on 2021-03-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('stockSymbol', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('sharesAmount', models.FloatField(default=0.0)),
            ],
        ),
    ]
