version: "3.9"
   
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: dockdockgoose
    command: mongod --auth
    volumes:
      - ./data-db:/data/db
    ports: 
      - 27017:27017
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - mongodb
  makemigrations:
    build: .
    command: python manage.py makemigrations
    volumes:
      - .:/code
    depends_on:
      - mongodb