# Generated by Django 3.0.5 on 2021-03-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEndStocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendstock',
            name='prevPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
